# Generated by Django 4.2.5 on 2023-09-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_profile_follow_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
