# Generated by Django 4.2.5 on 2023-09-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publicated_on',
        ),
    ]
