# Generated by Django 4.2.5 on 2023-09-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0002_remove_post_publicated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
